services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=stories_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '127.0.0.1:5432:5432'