spring:
  application:
    name: stories

  datasource:
    username: myuser
    password: secret
    url: "jdbc:postgresql://127.0.0.1:5432/stories_db"

  sql:
    init:
      mode: always

#  cloud:
#    aws:
#      secretsmanager:
#        region: eu-north-1

management:
  endpoints:
    web:
      exposure:
        include: health