name: Build and run test

on:
  push:
    branches: [ "dev",  ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: myuser
          POSTGRES_DB: stories_db
        ports:
          - '5432:5432'

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: ./gradlew build


      - name: Run tests (dev push)
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: ./gradlew test

      - name: Full build and tests (dev PR)
        if: github.event_name == 'pull_request' && github.base_ref == 'dev'
        run: ./gradlew build

      - name: Full build and tests (main PR)
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: ./gradlew build